### ISSUE TITLE
Possible Feature: Issue import

### ISSUE THREAD

**Issue by frodopwns** [drud/prepo#6]
Might be useful to be able to import issues from another repo using regex.

**Comment by rfay** [comment]
If it's a one-off effort, or just a few issues, https://github-issue-mover.appspot.com/ is pretty nice and leaves a good track of what it's done.

**Comment by frodopwns** [comment]
Do you think that this type of feature fits the idea of what Prepo is though? Sure most of the things it does can already be done with other tools. The question is would this functionality existing side-by-side with the other planned features offer value to the user? In the end its trivial to code imo.

Also consider the idea from the perspective of someone working on their free time and not necessarily someone who needs to just get from A to B quickly.

**Comment by rfay** [comment]
All *I* actually want from prepo is some labels on the repos I work with! Still looking forward to those being applied.

**Comment by frodopwns** [comment]
Ah...didn't realize you were waiting on that. They have only been applied to drud/general.

**Comment by cyberswat** [comment]
Thanks for submitting this.  Can you help us get this ticket into a state where it meets our [request guidelines](https://github.com/drud/community/blob/master/development/request_guidelines.md)?
