### ISSUE TITLE
Feature request: Add feature that allows the user to add build tools to repos by default

### ISSUE THREAD

**Issue by frodopwns** [drud/prepo#8]
I would like to initialize repos with https://github.com/drud/build-tools already inside.

**Comment by tannerjfco** [comment]
It would also be great to have PR/Issue templates, readme/docs possibly - perhaps these all could be achieved by allowing to define a repo where the initial repo contents are maintained?

**Comment by frodopwns** [comment]
Yep I think that sounds like a good direction. Maybe the repo url and destination directory plus a post pull task that lets you run any of the other task actions right after the resources are pulled in. Maybe you accomplish the copying of Makefile.example to Makefile.

**Comment by frodopwns** [comment]
test

**Comment by frodopwns** [comment]
test

**Comment by cyberswat** [comment]
Thanks for submitting this.  Can you help us get this ticket into a state where it meets our [request guidelines](https://github.com/drud/community/blob/master/development/request_guidelines.md)?
